version: "3"
services:
  database:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: strapyard
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
  redis:
    image: docker.io/bitnami/redis:6.0-debian-10
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - redis-data:/bitnami/redis/data

volumes:
  redis-data:
  database-data:
